# Data Aggregation

   * The process of compiling typically large amounts of information from a given dataset and     organizing into a more consumable and comprehensive medium is called Data Aggregation

#### Import necessary modules

In [1]:
import pandas as pd 
import numpy as np

#### Load a csv file into a Pandas DataFrame

In [2]:
dataset = pd.read_csv("World Happiness Data 2016.csv")

In [3]:
dataset.head()

,Country,Region,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Denmark,Western Europe,1,7.526,7.460,7.592,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,Western Europe,2,7.509,7.428,7.590,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
2,Iceland,Western Europe,3,7.501,7.333,7.669,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137
3,Norway,Western Europe,4,7.498,7.421,7.575,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465
4,Finland,Western Europe,5,7.413,7.351,7.475,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2.82596

### unique() function
   * It is used to get unique values of series object
   * Uniques are returned in order of appearence
   * Syntax: Series.unique(self)

In [4]:
region = dataset["Region"].unique()

In [5]:
region

array(['Western Europe', 'North America', 'Australia and New Zealand',
       'Middle East and Northern Africa', 'Latin America and Caribbean',
       'Southeastern Asia', 'Central and Eastern Europe', 'Eastern Asia',
       'Sub-Saharan Africa', 'Southern Asia'], dtype=object)

### Extracting countries lying in Southeastern Asian region

In [6]:
dataset[dataset["Region"] == "Southeastern Asia"]

,Country,Region,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
21,Singapore,Southeastern Asia,22,6.739,6.674,6.804,1.64555,0.86758,0.94719,0.48770,0.46987,0.32706,1.99375
32,Thailand,Southeastern Asia,33,6.474,6.396,6.552,1.08930,1.04477,0.64915,0.49553,0.02833,0.58696,2.57960
46,Malaysia,Southeastern Asia,47,6.005,5.921,6.089,1.25142,0.88025,0.62366,0.39031,0.09081,0.41474,2.35384
78,Indonesia,Southeastern Asia,79,5.314,5.237,5.391,0.95104,0.87625,0.49374,0.39237,0.00322,0.56521,2.03171
81,Philippines,Southeastern Asia,82,5.279,5.160,5.398,0.81217,0.87877,0.47036,0.54854,0.11757,0.21674,2.23484
95,Vietnam,Southeastern Asia,96,5.061,4.991,5.131,0.74037,0.79117,0.66157,0.55954,0.11556,0.25075,1.94180
101,Laos,Southeastern Asia,102,4.876,4.742,5.010,0.68042,0.54970,0.38291,0.52168,0.22423,0.43079,2.08637
118,Myanmar,Southeastern Asia,119,4.395,4.327,4.463,0.34112,0.69981,0.39880,0.42692,0.20243,0.81971,1.50655
139,Cambodia,Southeastern Asia,140,3.907,3.798,4.016,0.55604,0.53750,0.42494,0.58852,0.08092,0.40339,1.31573

### Finding average happiness score for each region using for loop

In [7]:
region_avg_happ_score = {}

for i in region: #Wester Europe
    avg_happ_score = dataset[dataset["Region"] == i]["Happiness Score"].mean()
    region_avg_happ_score[i] = round(avg_happ_score,2)

In [8]:
region_avg_happ_score

{'Western Europe': 6.69,
 'North America': 7.25,
 'Australia and New Zealand': 7.32,
 'Middle East and Northern Africa': 5.39,
 'Latin America and Caribbean': 6.1,
 'Southeastern Asia': 5.34,
 'Central and Eastern Europe': 5.37,
 'Eastern Asia': 5.62,
 'Sub-Saharan Africa': 4.14,
 'Southern Asia': 4.56}

#### Groupby on Region

In [9]:
region_group = dataset.groupby("Region")

In [10]:
region_group

#### Mean of Western Europe

In [11]:
region_group.get_group("Western Europe").mean()

Happiness Rank                   29.190476
Happiness Score                   6.685667
Lower Confidence Interval         6.604571
Upper Confidence Interval         6.766762
Economy (GDP per Capita)          1.417056
Family                            1.042452
Health (Life Expectancy)          0.825754
Freedom                           0.477587
Trust (Government Corruption)     0.232544
Generosity                        0.304715
Dystopia Residual                 2.385576
dtype: float64

### Finding averege happiness score for each region using group

In [12]:
region_avg_happ_score = {}

for i in region:
    avg_happ_score = region_group.get_group(i)["Happiness Score"].mean()
    region_avg_happ_score[i] = round(avg_happ_score,2)

In [13]:
region_avg_happ_score

{'Western Europe': 6.69,
 'North America': 7.25,
 'Australia and New Zealand': 7.32,
 'Middle East and Northern Africa': 5.39,
 'Latin America and Caribbean': 6.1,
 'Southeastern Asia': 5.34,
 'Central and Eastern Europe': 5.37,
 'Eastern Asia': 5.62,
 'Sub-Saharan Africa': 4.14,
 'Southern Asia': 4.56}

In [14]:
region_group["Happiness Score"].mean()

Region
Australia and New Zealand          7.323500
Central and Eastern Europe         5.370690
Eastern Asia                       5.624167
Latin America and Caribbean        6.101750
Middle East and Northern Africa    5.386053
North America                      7.254000
Southeastern Asia                  5.338889
Southern Asia                      4.563286
Sub-Saharan Africa                 4.136421
Western Europe                     6.685667
Name: Happiness Score, dtype: float64

### Finding averages of all columns under grouped regions

In [15]:
region_group.mean().round(2)

,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
Region,,,,,,,,,,,
Australia and New Zealand,8.50,7.32,7.25,7.39,1.40,1.14,0.84,0.57,0.37,0.48,2.51
Central and Eastern Europe,78.45,5.37,5.28,5.46,1.05,0.86,0.63,0.30,0.09,0.17,2.27
Eastern Asia,67.17,5.62,5.55,5.70,1.28,0.91,0.81,0.39,0.12,0.22,1.90
Latin America and Caribbean,48.33,6.10,5.98,6.23,0.99,0.90,0.61,0.43,0.11,0.21,2.86
Middle East and Northern Africa,78.11,5.39,5.27,5.50,1.14,0.70,0.62,0.31,0.16,0.19,2.28
North America,9.50,7.25,7.18,7.33,1.47,1.07,0.80,0.53,0.23,0.43,2.72
Southeastern Asia,80.00,5.34,5.25,5.43,0.90,0.79,0.56,0.49,0.15,0.45,2.00
Southern Asia,111.71,4.56,4.49,4.64,0.66,0.48,0.45,0.35,0.10,0.34,2.17
Sub-Saharan Africa,129.66,4.14,4.02,4.25,0.47,0.59,0.24,0.32,0.12,0.23,2.17
Western Europe,29.19,6.69,6.60,6.77,1.42,1.04,0.83,0.48,0.23,0.30,2.39

#### Size of all grouped regions

In [16]:
region_group.size()

Region
Australia and New Zealand           2
Central and Eastern Europe         29
Eastern Asia                        6
Latin America and Caribbean        24
Middle East and Northern Africa    19
North America                       2
Southeastern Asia                   9
Southern Asia                       7
Sub-Saharan Africa                 38
Western Europe                     21
dtype: int64

### Finding Aggregate Function of "Happiness Score"

In [17]:
happiness_score = region_group["Happiness Score"]

In [18]:
agg_func = happiness_score.agg(["mean","max","min","count","sum"])

In [20]:
agg_func.columns= ["Happiness_mean","Happiness_max","Happiness_min","Happiness_count","Happiness_sum"]

In [21]:
agg_func

,Happiness_mean,Happiness_max,Happiness_min,Happiness_count,Happiness_sum
Region,,,,,
Australia and New Zealand,7.323500,7.334,7.313,2,14.647
Central and Eastern Europe,5.370690,6.596,4.217,29,155.750
Eastern Asia,5.624167,6.379,4.907,6,33.745
Latin America and Caribbean,6.101750,7.087,4.028,24,146.442
Middle East and Northern Africa,5.386053,7.267,3.069,19,102.335
North America,7.254000,7.404,7.104,2,14.508
Southeastern Asia,5.338889,6.739,3.907,9,48.050
Southern Asia,4.563286,5.196,3.360,7,31.943
Sub-Saharan Africa,4.136421,5.648,2.905,38,157.184
Western Europe,6.685667,7.526,5.033,21,140.399

### Pivot Table of DataSet

In [23]:
dataset.pivot_table(index = "Region", values = "Happiness Score", aggfunc = ["mean","max","min"], margins = True)

,mean,max,min
,Happiness Score,Happiness Score,Happiness Score
Region,,,
Australia and New Zealand,7.323500,7.334,7.313
Central and Eastern Europe,5.370690,6.596,4.217
Eastern Asia,5.624167,6.379,4.907
Latin America and Caribbean,6.101750,7.087,4.028
Middle East and Northern Africa,5.386053,7.267,3.069
North America,7.254000,7.404,7.104
Southeastern Asia,5.338889,6.739,3.907
Southern Asia,4.563286,5.196,3.360
Sub-Saharan Africa,4.136421,5.648,2.905
Western Europe,6.685667,7.526,5.033
All,5.382185,7.526,2.905